addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.4.1")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"        % "0.9.31")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.4.6")
addCompilerPlugin("org.typelevel"        % "kind-projector"      % "0.13.2" cross CrossVersion.full)
addCompilerPlugin("org.scalamacros"      % "paradise"            % "2.1.1" cross CrossVersion.full)
addCompilerPlugin("com.olegpy"          %% "better-monadic-for"  % "0.3.1")
addSbtPlugin("io.spray"                  % "sbt-revolver"        % "0.9.1")
addSbtPlugin("com.github.sbt"            % "sbt-native-packager" % "1.9.9")
